# Generated by Django 6.0.2 on 2026-02-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва заняття')),
                ('description', models.TextField(verbose_name='Опис заняття')),
            ],
            options={
                'verbose_name': 'Додаткове заняття',
                'verbose_name_plural': 'Додаткові заняття',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('middle_name', models.CharField(max_length=100, verbose_name='По батькові')),
                ('description', models.TextField(verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='П.І.Б. учня')),
                ('age', models.PositiveIntegerField(verbose_name='Вік')),
                ('school_class', models.CharField(max_length=20, verbose_name='Клас')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_admin.extralesson', verbose_name='Додаткове заняття')),
            ],
            options={
                'verbose_name': 'Учень',
                'verbose_name_plural': 'Учні',
            },
        ),
        migrations.AddField(
            model_name='extralesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.teacher', verbose_name='Викладач'),
        ),
    ]
